version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    expose:
      - "9000"  
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql 
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=intern_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intern_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
